### ISSUE TITLE
Command failed: No such file or directory

### ISSUE THREAD

**Issue by muescha** [shemeshg/cakebrewjs#2]
i get this error:

```shell
Command failed: /usr/local/bin/brew info --installed --json=v2 /bin/sh: /usr/local/bin/brew: No such file or directory
```

it seems my brew is installed in a different location:

```shell
$ which brew
/opt/homebrew/bin/brew
```

ScreenShot: 

<img width="799" alt="Bildschirmfoto 2022-06-09 um 11 08 25" src="https://user-images.githubusercontent.com/184316/172810351-1cfe994d-815c-4d43-9e79-c8589824bebe.png">

**Comment by shemeshg** [comment]
Tried to get "which brew" to work, but I was not successful in loading default zshprofile to the 
```
require("electron").remote.require("child_process
```
so I have added a configuration field instead.

![image](https://user-images.githubusercontent.com/8200598/172946088-66e0446a-f280-4104-80de-dda18fabe89a.png)

**Comment by muescha** [comment]
for convinience of the user: 

### 1) check on startup 

maybe you do a check the current brew location (from setup) on startup and if not the right path - then point to the settings - or open the settings dialog direct


### 2) hint how to find out the path

you should also add to the Settings:

```
Brew location (do `which brew`):
```
