### ISSUE TITLE
stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by ricounet67** [shemeshg/cakebrewjs#4]
When I run cakebrewjs for the first time, I have the following error message: stdout maxBuffer length exceeded
Then I have no casks or formula displayed in the application.
How can I expand the maxBuffer value ?

**Comment by shemeshg** [comment]
Hi
## Can you post the 
```bash
% /usr/local/bin/brew info --installed --json=v2 > /tmp/l; du -h /tmp/l
   796K	/tmp/l
%
```
So I can estimate what reasonably value is?



## It's a parameter I can fix here
https://github.com/shemeshg/cakebrewjs/blob/763c6dcda0e89c1d94e12d4b8ca1e60a91d9b9c3/src/src/ShellCmd.ts#L52

See:
https://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

Thanks
shemeshg

**Comment by ricounet67** [comment]
1.9M

**Comment by shemeshg** [comment]
I'll make it 4M max with option to change in localStorage

Thanks
