### ISSUE TITLE
after startup brew not found

### ISSUE THREAD

**Issue by GerLan** [shemeshg/cakebrewjs#6]
Hi, 
I installed homebrew and cakebrewjs fresh on an M1 Macbook pro.
After starting following error:
Command failed: /usr/local/bin/brew update /bin/sh: /usr/local/bin/brew: No such file or directory

I think it is because on M1 mac the homebrew directory is in /opt/homebrew/

**Comment by shemeshg** [comment]
Hi

# Please try

```
% which brew
/usr/local/bin/brew
%
```

and past that in 

![image](https://user-images.githubusercontent.com/8200598/199262988-5d63fde3-ebb8-4ae1-9610-e68896d9d859.png)

# Tell me if you have a way to sense the brew location from the `nodejs` `pipe`

**Comment by GerLan** [comment]
thanks! I had "overseen" the "settings" in about :)
