### ISSUE TITLE
error message when installing or updating (macOS Ventura Terminal authorization)

### ISSUE THREAD

**Issue by georgemoodier** [shemeshg/cakebrewjs#9]
Ahoy there, I’ve switched to this app since I noticed that cakebrew is no longer receiving updates but I’ve encountered a very annoying problem:

this error message appears whenever I try to install or update a cask or formula:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/84156418/210782840-81a3a366-8ce4-45af-a3c7-6eb1b6919d49.png">

clicking the “i” button gives a path to the .sh document, which is usually in the “tmp” folder:
<img width="495" alt="Screenshot 1401-10-15 at 16 15 21" src="https://user-images.githubusercontent.com/84156418/210783313-f76ab9d1-d9f4-4dc2-92e8-72442af029af.png">

clicking on the .sh file specified on the path brings you to the hidden tmp folder with the specific file highlighted, once there you can click on the file to initiate whatever it was that you were doing (installing, updating, etc.).

Is there anything I could do to not have to do this process constantly?

**Comment by shemeshg** [comment]
Hi

# I do have full access for terminal, but i'm not sure it is required.
![image](https://user-images.githubusercontent.com/8200598/210811452-d26877dc-baba-46b2-968a-77346f80efcb.png)


* tell me if you can fine tune that

# Maybe this would be sufficient 

When the application is first open, it asks you "allow access to drives" 

You can 

* delete the app from:

![image](https://user-images.githubusercontent.com/8200598/210810365-3447637b-7c70-4a54-8b58-8d07039dcc62.png)

and it will ask you again.

or:

Mark it is you see in the photo.

# tell me if it helps or you have better suggestion

Maybe providing terminal same authorization as cakebrewjs in `files and folders`?

**Comment by georgemoodier** [comment]
weird, seems like cakebrewjs never asks for permission, no matter if it gets downloaded through homebrew or not, I can only give it full disk access.

**Comment by shemeshg** [comment]
> weird, seems like cakebrewjs never asks for permission, no matter if it gets downloaded through homebrew or not, I can only give it full disk access.

And you sure it does not exists in your `Files and Folder` authorization unselected?

* for the Terminal app, I have it grayed out in `Files and Folder` and can only `full disk access` too
* You will still need to provide access to the terminal too (I guess)

**Comment by georgemoodier** [comment]
nope, it only shows up because off its full disk access

<img width="498" alt="image" src="https://user-images.githubusercontent.com/84156418/210823109-b530e0ab-83ea-4235-bf73-7dd45259a504.png">


terminal also only has full disk access, btw

**Comment by shemeshg** [comment]
Can you verify the same for the `terminal app`

* for the Terminal app, I have it grayed out in Files and Folder and can only full disk access too
* You will still need to provide access to the terminal too (`Full disk`) 

After all, the terminal app is the one that complains about lack of authorization.

## The reasons for invoking some processes in external terminal is that

Some processes (Like install) might require user intervention.

**Comment by georgemoodier** [comment]
> for the Terminal app, I have it grayed out in Files and Folder and can only full disk access too

yes, terminal also only has full disk access for me:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/84156418/210824891-89c665ae-040b-4162-b378-aded040db020.png">

**Comment by shemeshg** [comment]
It is os ventura + Terminal app specific issue, 

https://stackoverflow.com/questions/74187734/launchpackager-command-can-t-be-opened

I'll think of something (Maybe option to select external terminal...)

Thanks

**Comment by shemeshg** [comment]
As stackoverflow suggest using iTerm

* First:  Install iTerm2
`brew --cask install iterm2

1. `brew upgrade cakebrewjs` to 1.4.1 .
2. In the about page select Terminal application "iTerm"
3. Ensure iTerm has full access
4. click "run doctor" from "home" tab

Post here if it works or not...

**Comment by georgemoodier** [comment]
yup, it’s good now, just a simple click and all of my formulas are updated :). hope the whole terminal issue gets fixed.
